ListView of activities - slidable actions
AppCreativity/Kliva pull request #115
Opened 2016-11-15 23:07 UTC by punker76

This PR adds two actions to the activity list.

- Add the UWP Community Toolkit, so we can use the SlidableListItem for this stuff
- Left command selects activity and make the Kudos and/or open the kudos list
- Right command selects activity and opens the comment input dialog (and after this the comment list)
- Also fix not showing comment pivot after swipe it

open

- [ ] slidable actions should not happen for own activities

Closes #23 ListView of activities - use swipe to 'like'

2016-11-15 23:37 UTC, Depechie reviewed
Looking great so far, only the trigger after having given Kudos is a blocking issue right now.

2016-11-15 23:37 UTC, Depechie commented on src/Kliva/ViewModels/ActivityDetailViewModel.cs
> +            ServiceLocator.Current.GetInstance<IMessenger>().Send<PivotMessage<ActivityPivots>>(new PivotMessage<ActivityPivots>(ActivityPivots.Comments, true, true), Tokens.ActivityPivotMessage);
Shouldn't we only show the comments tab, if a comment was entered? So I would move this Send<> back into the if(){...}

2016-11-15 23:37 UTC, Depechie commented on src/Kliva/ViewModels/MainViewModel.cs
> +            MessengerInstance.Send<ActivitySummaryCommentMessage>(new ActivitySummaryCommentMessage(_selectedActivity));
Why use the internal backing field? Normally we would always tend to use the property... so MessengerInstance.Send<ActivitySummaryCommentMessage>(new ActivitySummaryCommentMessage(SelectedActivity));

2016-11-15 23:37 UTC, Depechie commented on src/Kliva/XAMLResources/DataTemplates.xaml
> +                <core:DataTriggerBehavior Binding="{x:Bind HasKudoed, Mode=OneWay}" ComparisonCondition="Equal" Value="True">
This does not trigger 'after' given a Kudos. This only works when loading the list with items. Even setting it to TwoWay has no effect.
We need to see how we can fix this...

2016-11-16 08:04 UTC, punker76 commented on src/Kliva/ViewModels/MainViewModel.cs
> +            MessengerInstance.Send<ActivitySummaryCommentMessage>(new ActivitySummaryCommentMessage(_selectedActivity));
My fault (copy&paste) will change it

2016-11-16 08:10 UTC, punker76 commented on src/Kliva/XAMLResources/DataTemplates.xaml
> +                <core:DataTriggerBehavior Binding="{x:Bind HasKudoed, Mode=OneWay}" ComparisonCondition="Equal" Value="True">
Yeah, cause ActivitySummary isn't updated after changes (it concerns also the other properties). For the first I can trigger the change of the property by hand.

2016-11-16 08:11 UTC, punker76 commented on src/Kliva/ViewModels/ActivityDetailViewModel.cs
> +            ServiceLocator.Current.GetInstance<IMessenger>().Send<PivotMessage<ActivityPivots>>(new PivotMessage<ActivityPivots>(ActivityPivots.Comments, true, true), Tokens.ActivityPivotMessage);
Ok

2016-11-16 08:14 UTC, Depechie commented on src/Kliva/XAMLResources/DataTemplates.xaml
> +                <core:DataTriggerBehavior Binding="{x:Bind HasKudoed, Mode=OneWay}" ComparisonCondition="Equal" Value="True">
Indeed I would suggest to manually search for the changed ActivitySummary inside the ActivityIncrementalCollection and update the property by hand if possible.

2016-11-16 08:38 UTC, bartlannoeye requested changes

2016-11-16 08:38 UTC, bartlannoeye commented on src/Kliva/ViewModels/ActivityDetailViewModel.cs
> +        public RelayCommand KudosCommand => _kudosCommand ?? (_kudosCommand = new RelayCommand(async () => await OnKudosAsync(this.SelectedActivity.Id)));
no need for using this.

2016-11-16 08:38 UTC, bartlannoeye commented on src/Kliva/ViewModels/MainViewModel.cs
> +        private async Task OnKudosAsync(ActivitySummary activitySummary)
private methods below public methods

2016-11-16 08:38 UTC, bartlannoeye commented on src/Kliva/ViewModels/MainViewModel.cs
> +            if (activitySummary != this.SelectedActivity)
no need for this.

2016-11-16 08:38 UTC, bartlannoeye commented on src/Kliva/ViewModels/MainViewModel.cs
> +        private async Task OnKudosAsync(ActivitySummary activitySummary)
why async Task? I don't see async code

2016-11-16 08:38 UTC, bartlannoeye commented on src/Kliva/ViewModels/MainViewModel.cs
> +        private async Task OnCommentAsync(ActivitySummary activitySummary)
idem on async

2016-11-16 08:41 UTC, punker76 commented on src/Kliva/ViewModels/MainViewModel.cs
> +            if (activitySummary != this.SelectedActivity)
> this could happen if we use the mouse to swipe and move the mouse outside the ListView and release it there

2016-11-16 08:42 UTC, Depechie commented on src/Kliva/ViewModels/MainViewModel.cs
> +            if (activitySummary != this.SelectedActivity)
Bart means, no need for the 'this'keyword ;)
The actual code IS needed of course

2016-11-16 08:42 UTC, punker76 commented on src/Kliva/ViewModels/MainViewModel.cs
> +            if (activitySummary != this.SelectedActivity)
uups

2016-11-16 08:42 UTC, bartlannoeye commented on src/Kliva/ViewModels/MainViewModel.cs
> +            if (activitySummary != this.SelectedActivity)
meant the code this.SelectedActivity should simply be SelectedActivity, sorry for inclarity :)
I'm quite ocd on unused/unnecessary code ;)

2016-11-16 08:43 UTC, Depechie commented on src/Kliva/ViewModels/ActivityDetailViewModel.cs
> +        public RelayCommand KudosCommand => _kudosCommand ?? (_kudosCommand = new RelayCommand(async () => await OnKudosAsync(this.SelectedActivity.Id)));
Meaning the 'this' keyword

2016-11-16 09:00 UTC, Depechie commented on src/Kliva/ViewModels/MainViewModel.cs
> +        public RelayCommand<ActivitySummary> CommentCommand => _commentCommand ?? (_commentCommand = new RelayCommand<ActivitySummary>(OnCommentAsync));
Jan, Bart meant that you created 2 methods called OnKudosAsync and OnCommentAsync, but the code in these 2 methods don't contain any Async references... You only call MessengerInstance.Send<...>

So his suggestion : Rename the methods to OnKudos and OnComment!

2016-11-16 09:07 UTC, bartlannoeye approved these changes

2016-11-17 20:25 UTC, merged